### ISSUE TITLE
wrong answer

### ISSUE THREAD

**Issue by c-cube** [epfl-lara/inox#7]
This problem should be "unsat" (unless I wrote it wrong?), but inox reports "sat"

version: 5a8f96ea5f9158d9f548af18215db17599839ca8
backends z3 and cvc4 both trigger the error.

```smt
; UNSAT

; the classic "pigeonhole" principle: trying to fit 5 pigeons
; into 4 holes is bound to fail.

(declare-sort hole 0)
(declare-fun h1 () hole)
(declare-fun h2 () hole)
(declare-fun h3 () hole)
(declare-fun h4 () hole)
(declare-fun p1 () hole)
(declare-fun p2 () hole)
(declare-fun p3 () hole)
(declare-fun p4 () hole)
(declare-fun p5 () hole)
(assert
 (and
  (not (= h1 h2))
  (not (= h1 h3))
  (not (= h1 h4))
  (not (= h2 h3))
  (not (= h2 h4))
  (not (= h3 h4))
 ))
(assert
  (and
    (not (= p1 p2))
    (not (= p1 p3))
    (not (= p1 p4))
    (not (= p1 p5))
    (not (= p2 p3))
    (not (= p2 p4))
    (not (= p2 p5))
    (not (= p3 p4))
    (not (= p3 p5))
    (not (= p4 p5))
  ))
; map pigeons to holes
(assert
 (forall ((p hole)) (or (= p h1) (= p h2) (= p h3) (= p h4))))
(check-sat)
```

**Comment by samarion** [comment]
This is due to a limitation in the quantifier instantiation module of Inox. Equalities are not considered as triggers for quantifier instantiation. I used to have a warning about such models, I must have removed it at some point... I'll look into reintroducing the warning.

I don't think I'll be changing this behavior. Quantifiers were introduced into Inox to enable specification about first-class functions and will therefore almost always have some associated triggers. The overhead that would come from equality triggers would probably be prohibitive for many interesting benchmarks and doesn't provide better completeness bounds.

Expressing finiteness of some sort can be done through either exhaustively listing the possible equalities or using an ADT invariant on the sort.
```
(declare-datatypes () ((hole (hole1 (id Int)))))
(datatype-invariant h hole (and (<= 1 (id h)) (<= (id h) 4)))
```

**Comment by samarion** [comment]
By the way, the above change doesn't fix the benchmark in the current version, I'll push the fix in a minute. I just want to check https://github.com/epfl-lara/inox/issues/8 first.

**Comment by c-cube** [comment]
I'll stick to the `--checkmodels` option with the current framework.

Fyi, I'm writing some benchmarks for a paper, in the fragment with datatypes, bounded quantifiers (i.e. uninterpreted types are considered as finite types), and recursive functions.

**Comment by samarion** [comment]
We typically assume that quantifiers range over unbounded types (and uninterpreted types have infinite cardinality) so I guess we won't shine on these benchmarks.

The quantifier instantiation technique remains sound for proofs even when the quantified proposition doesn't belong to our preferred fragment so I'd rather only throw warnings in case of satisfiability. I'll make sure we complain when necessary.

**Comment by c-cube** [comment]
Right, it depends on whether you look for proofs or for models :-)
It's more or less fine by me the way things work right now because of `--checkmodels`, and it's a small benchmark anyway.

**Comment by samarion** [comment]
Inox will now complain since ee9f223eaa89fc8a5b6fe4817d2bfeb1a2042e21
